### ISSUE TITLE
Not able boot application due to css build

### ISSUE THREAD

**Issue by fitterfly-divyesh** [creyes-dev/twitter-rails7#1]
Hi Reyes

I tried running the application but its not booting up, it is showing following error.

```Error: Can't find stylesheet to import.
00:10:15 css.1  |   ╷
00:10:15 css.1  | 3 │ @import './getskills/vendor/jquery-nice-select/nice-select';
00:10:15 css.1  |   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:10:15 css.1  |   ╵
00:10:15 css.1  |   app/assets/stylesheets/application.bootstrap.scss 3:9  root stylesheet```

**Comment by creyes-dev** [comment]
That is correct, it's supposed to be like that because I can't upload getskills template files here, if I do it then I lose the license because it's a paid template

**Comment by fitterfly-divyesh** [comment]
Oh, Okay
Is there any way I can boot this application up ?
